//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int ID_Account { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> DaKichHoat { get; set; }
        public Nullable<byte> PhanQuyen { get; set; }
        public Nullable<bool> DaKhoa { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string GhiChu { get; set; }
    }
}
