//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int staff { get; set; }
        public int PDistributor { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string place { get; set; }
        public Nullable<bool> isComplete { get; set; }
        public string result { get; set; }
    
        public virtual PotentialDistributor PotentialDistributor { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
