//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchDetail
    {
        public int IdBatch { get; set; }
        public int IdProduct { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> ExipreDate { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Product Product { get; set; }
    }
}
