//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDotHang
    {
        public int ID_DotHang { get; set; }
        public int ID_SanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> HSD { get; set; }
    
        public virtual DotHang DotHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
