//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contract
    {
        public int idContract { get; set; }
        public Nullable<System.DateTime> beginDate { get; set; }
        public Nullable<System.DateTime> expiredDate { get; set; }
        public Nullable<decimal> minOrderTotalValue { get; set; }
        public Nullable<decimal> maxDebt { get; set; }
        public Nullable<byte> commission { get; set; }
        public Nullable<bool> disType { get; set; }
        public string area { get; set; }
        public Nullable<bool> status { get; set; }
        public string note { get; set; }
        public Nullable<int> distributor { get; set; }
        public Nullable<int> representative { get; set; }
        public Nullable<int> staff { get; set; }
    
        public virtual Representative Representative1 { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Distributor Distributor1 { get; set; }
    }
}
