//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DoanhThu
    {
        public int ID_BaoCaoDoanhThu { get; set; }
        public int ID_LoaiSP { get; set; }
        public Nullable<int> DonGiaBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual BaoCaoDoanhThu BaoCaoDoanhThu { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
