//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryOrder()
        {
            this.Bills = new HashSet<Bill>();
            this.DetailedDeliveryOrders = new HashSet<DetailedDeliveryOrder>();
        }
    
        public int idDeliveryOrder { get; set; }
        public string recipient { get; set; }
        public string deliveryAdd { get; set; }
        public Nullable<decimal> totalPurchase { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string description { get; set; }
        public Nullable<int> idOrder { get; set; }
        public Nullable<int> idStaff { get; set; }
        public Nullable<int> idDistributor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual Distributor Distributor { get; set; }
        public virtual Order Order { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailedDeliveryOrder> DetailedDeliveryOrders { get; set; }
    }
}
