//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailedDeliveryOrder
    {
        public int idDeliveryOrder { get; set; }
        public int idProduct { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> promoQuantity { get; set; }
        public string note { get; set; }
    
        public virtual DeliveryOrder DeliveryOrder { get; set; }
        public virtual Product Product { get; set; }
    }
}
