//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_NPPEntities : DbContext
    {
        public QL_NPPEntities()
            : base("name=QL_NPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<BatchDetail> BatchDetails { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Consignee> Consignees { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Debt> Debts { get; set; }
        public virtual DbSet<Distributor> Distributors { get; set; }
        public virtual DbSet<Log_Login> Log_Login { get; set; }
        public virtual DbSet<Log_Order> Log_Order { get; set; }
        public virtual DbSet<Log_OrderDetail> Log_OrderDetail { get; set; }
        public virtual DbSet<Log_Product> Log_Product { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<PaySlip> PaySlips { get; set; }
        public virtual DbSet<PotentialDistributor> PotentialDistributors { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<PromotionGift> PromotionGifts { get; set; }
        public virtual DbSet<PromotionProduct> PromotionProducts { get; set; }
        public virtual DbSet<Representative> Representatives { get; set; }
        public virtual DbSet<ReturnBase> ReturnBases { get; set; }
        public virtual DbSet<ReturnDetail> ReturnDetails { get; set; }
        public virtual DbSet<ReturnRequest> ReturnRequests { get; set; }
        public virtual DbSet<ReturnRequestDetail> ReturnRequestDetails { get; set; }
        public virtual DbSet<SalesReport> SalesReports { get; set; }
        public virtual DbSet<SalesReportDetail> SalesReportDetails { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Storage> Storages { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<DeliveryOrder> DeliveryOrders { get; set; }
        public virtual DbSet<DetailedDeliveryOrder> DetailedDeliveryOrders { get; set; }
    }
}
