//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatHang()
        {
            this.DonGiaoHangs = new HashSet<DonGiaoHang>();
            this.Log_ChiTietDDH = new HashSet<Log_ChiTietDDH>();
            this.NguoiLienHeGiaoHangs = new HashSet<NguoiLienHeGiaoHang>();
        }
    
        public int ID_DonHang { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<bool> HinhThucGiaoHang { get; set; }
        public Nullable<bool> HinhThucThanhToan { get; set; }
        public Nullable<System.DateTime> NgayGiaoDuKien { get; set; }
        public Nullable<byte> TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> ID_NPP { get; set; }
        public Nullable<int> ID_NguoiLienHe { get; set; }
        public Nullable<int> ID_NhanVien { get; set; }
        public string MoTa { get; set; }
    
        public virtual NguoiLienHeGiaoHang NguoiLienHeGiaoHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhaPhanPhoi NhaPhanPhoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonGiaoHang> DonGiaoHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log_ChiTietDDH> Log_ChiTietDDH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiLienHeGiaoHang> NguoiLienHeGiaoHangs { get; set; }
    }
}
