//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonYCDoiTra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonYCDoiTra()
        {
            this.CTDonYCDoiTras = new HashSet<CTDonYCDoiTra>();
        }
    
        public int ID_DonYCDT { get; set; }
        public Nullable<System.DateTime> NgayLapDon { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> HinhThuc { get; set; }
        public Nullable<int> NPP { get; set; }
        public Nullable<int> Kho { get; set; }
        public Nullable<int> NhanVien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonYCDoiTra> CTDonYCDoiTras { get; set; }
        public virtual Kho Kho1 { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual NhaPhanPhoi NhaPhanPhoi { get; set; }
    }
}
