//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int ID_HoaDon { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<byte> LoaiHoaDon { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> ID_GiaoHang { get; set; }
        public Nullable<int> ID_NhanVien { get; set; }
        public Nullable<int> ID_NPP { get; set; }
    
        public virtual DonGiaoHang DonGiaoHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhaPhanPhoi NhaPhanPhoi { get; set; }
    }
}
