//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public int ID_HopDong { get; set; }
        public Nullable<System.DateTime> TGBatDau { get; set; }
        public Nullable<System.DateTime> TGKetThuc { get; set; }
        public Nullable<decimal> GTDonHangNhoNhat { get; set; }
        public Nullable<decimal> CongNoToiDa { get; set; }
        public Nullable<byte> TienHoaHong { get; set; }
        public Nullable<bool> LoaiPhanPhoi { get; set; }
        public string KhuVuc { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> NhaPhanPhoi { get; set; }
        public Nullable<int> NguoiDaiDien { get; set; }
        public Nullable<int> NhanVien { get; set; }
    
        public virtual NguoiDaiDien NguoiDaiDien1 { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual NhaPhanPhoi NhaPhanPhoi1 { get; set; }
    }
}
