//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_ChiTietDDH
    {
        public int ID_Log { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> SoLuongCu { get; set; }
        public Nullable<int> SoLuongMoi { get; set; }
        public string LyDo { get; set; }
        public Nullable<int> ID_DonHang { get; set; }
        public Nullable<int> ID_SanPham { get; set; }
        public Nullable<int> ID_NhanVien { get; set; }
    
        public virtual DonDatHang DonDatHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
