//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Login
    {
        public long idLog { get; set; }
        public Nullable<int> idAccount { get; set; }
        public Nullable<System.DateTime> at_time { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
