//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_SanPham
    {
        public int ID_Log_SanPham { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> ID_NhanVien { get; set; }
        public Nullable<int> DonGiaCu { get; set; }
        public Nullable<int> DonGiaMoi { get; set; }
        public string LyDo { get; set; }
    }
}
