//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Product
    {
        public int idLog_Product { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> idStaff { get; set; }
        public Nullable<int> oldPrice { get; set; }
        public Nullable<int> newPrice { get; set; }
        public string description { get; set; }
    }
}
