//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDaiDien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDaiDien()
        {
            this.DoiTacs = new HashSet<DoiTac>();
            this.HopDongs = new HashSet<HopDong>();
        }
    
        public int ID_NDD { get; set; }
        public string TenNDD { get; set; }
        public string SoDT { get; set; }
        public string Email { get; set; }
        public string ChucVu { get; set; }
        public Nullable<int> DoiTac { get; set; }
        public Nullable<int> NhaPhanPhoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoiTac> DoiTacs { get; set; }
        public virtual DoiTac DoiTac1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong> HopDongs { get; set; }
        public virtual NhaPhanPhoi NhaPhanPhoi1 { get; set; }
    }
}
