//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiLienHeGiaoHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiLienHeGiaoHang()
        {
            this.DonDatHangs = new HashSet<DonDatHang>();
        }
    
        public int ID_NguoiLienHe { get; set; }
        public string HoTen { get; set; }
        public string SDT { get; set; }
        public Nullable<int> ID_NPP { get; set; }
        public Nullable<int> ID_DonHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatHang> DonDatHangs { get; set; }
        public virtual DonDatHang DonDatHang { get; set; }
        public virtual NhaPhanPhoi NhaPhanPhoi { get; set; }
    }
}
