//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Representative
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Representative()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public int idRepresentative { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string title { get; set; }
        public Nullable<int> PDistributor { get; set; }
        public Nullable<int> Distributor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual Distributor Distributor1 { get; set; }
        public virtual PotentialDistributor PotentialDistributor { get; set; }
    }
}
