//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReturnRequest()
        {
            this.ReturnRequestDetails = new HashSet<ReturnRequestDetail>();
            this.ReturnBases = new HashSet<ReturnBase>();
        }
    
        public int IdReturnRequest { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Note { get; set; }
        public Nullable<bool> ModeOfReturn { get; set; }
        public Nullable<int> Distributor { get; set; }
        public Nullable<int> Storage { get; set; }
        public Nullable<int> Staff { get; set; }
    
        public virtual Distributor Distributor1 { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Storage Storage1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnRequestDetail> ReturnRequestDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnBase> ReturnBases { get; set; }
    }
}
