//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReturnBase()
        {
            this.ReturnDetails = new HashSet<ReturnDetail>();
        }
    
        public int idReturn { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<bool> ModeOfReturn { get; set; }
        public Nullable<int> idDistributor { get; set; }
        public Nullable<int> idStorage { get; set; }
        public Nullable<int> idStaff { get; set; }
    
        public virtual Distributor Distributor { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Storage Storage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnDetail> ReturnDetails { get; set; }
    }
}
