//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnDetail
    {
        public int idReturn { get; set; }
        public int idProduct { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> ProductMoneyRefunding { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ReturnBase ReturnBase { get; set; }
    }
}
