//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDotHangs = new HashSet<ChiTietDotHang>();
            this.CT_GiaoHang = new HashSet<CT_GiaoHang>();
            this.CT_KhuyenMaiMua = new HashSet<CT_KhuyenMaiMua>();
            this.CTDonYCDoiTras = new HashSet<CTDonYCDoiTra>();
            this.CTPhieuDoiTras = new HashSet<CTPhieuDoiTra>();
            this.Log_ChiTietDDH = new HashSet<Log_ChiTietDDH>();
        }
    
        public int ID_SanPham { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<int> LoaiSP { get; set; }
        public Nullable<int> DonViTinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDotHang> ChiTietDotHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_GiaoHang> CT_GiaoHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_KhuyenMaiMua> CT_KhuyenMaiMua { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonYCDoiTra> CTDonYCDoiTras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuDoiTra> CTPhieuDoiTras { get; set; }
        public virtual DonViTinh DonViTinh1 { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log_ChiTietDDH> Log_ChiTietDDH { get; set; }
    }
}
