//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Storage()
        {
            this.ReturnRequests = new HashSet<ReturnRequest>();
            this.ReturnBases = new HashSet<ReturnBase>();
        }
    
        public int IdStorage { get; set; }
        public string HouseNumber_Street { get; set; }
        public string Ward_Commune { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string Description { get; set; }
        public Nullable<int> Distributor { get; set; }
    
        public virtual Distributor Distributor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnRequest> ReturnRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnBase> ReturnBases { get; set; }
    }
}
